from pathlib import Path
import re

SKILLS_FILE = Path("data/skills.txt")

with open(SKILLS_FILE, "r", encoding="utf-8") as file:
    SKILLS = [line.strip() for line in file if line.strip()]

SKILL_ALIASES = {
    "js": "JavaScript",
    "ts": "TypeScript",
    "react.js": "React",
    "reactjs": "React",
    "vue.js": "Vue.js",
    "vuejs": "Vue.js",
    "angular.js": "Angular",
    "angularjs": "Angular",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "express.js": "Express.js",
    "expressjs": "Express.js",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "scikit learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "np": "NumPy",
    "pd": "Pandas",
    "cv": "OpenCV",
    "gcp": "Google Cloud Platform",
    "google cloud": "Google Cloud Platform",
    "k8s": "Kubernetes",
    "gh": "GitHub",
    "gcp": "Google Cloud Platform",
    "amazon web services": "AWS",
    "microsoft azure": "Azure",
    "ms azure": "Azure",
    "ci cd": "CI/CD",
    "ci/cd": "CI/CD",
    "continuous integration": "CI/CD",
    "continuous deployment": "CI/CD",
    "cicd": "CI/CD",
    "rest": "REST API",
    "restful": "REST API",
    "rest apis": "REST API",
    "graphql api": "GraphQL",
    "machine learning ops": "MLOps",
    "machine-learning": "Machine Learning",
    "deep-learning": "Deep Learning",
    "natural language processing": "NLP",
    "computer-vision": "Computer Vision",
    "data-science": "Data Science",
    "data-analysis": "Data Analysis",
    "data-engineering": "Data Engineering",
    "project-management": "Project Management",
    "product-management": "Product Management",
    "user-experience": "UI/UX Design",
    "user interface": "UI/UX Design",
    "user experience": "UI/UX Design",
    "ux design": "UI/UX Design",
    "ui design": "UI/UX Design",
    "figma design": "Figma",
    "penetration testing": "Penetration Testing",
    "ethical hacking": "Penetration Testing",
    "network security": "Network Security",
    "information security": "Cybersecurity",
    "infosec": "Cybersecurity",
    "unit test": "Unit Testing",
    "integration test": "Integration Testing",
    "end to end testing": "End-to-End Testing",
    "e2e testing": "End-to-End Testing",
    "load testing": "Load Testing",
    "performance testing": "Performance Testing",
    "security testing": "Security Testing",
    "api testing": "API Testing",
    "dev ops": "DevOps",
    "site reliability": "SRE",
    "site reliability engineering": "SRE",
    "platform engineering": "Platform Engineering",
    "serverless computing": "Serverless",
    "aws lambda": "AWS Lambda",
    "google cloud functions": "Google Cloud Functions",
    "azure functions": "Azure Functions",
    "tailwind": "Tailwind CSS",
    "material design": "Material UI",
    "material-ui": "Material UI",
    "adobe xd": "Adobe XD",
    "google analytics": "Google Analytics",
    "seo optimization": "SEO",
    "search engine optimization": "SEO",
    "agile methodology": "Agile",
    "scrum methodology": "Scrum",
    "kanban methodology": "Kanban",
    "technical writing": "Technical Writing",
    "public speaking": "Public Speaking",
    "conflict resolution": "Conflict Resolution",
    "emotional intelligence": "Emotional Intelligence",
    "budget management": "Budget Management",
    "risk management": "Risk Management",
    "quality assurance": "Quality Assurance",
    "test automation": "Selenium",
    "automated testing": "Selenium",
    "nosql": "MongoDB",
    "relational database": "PostgreSQL",
    "rdbms": "PostgreSQL",
    "document database": "MongoDB",
    "key value store": "Redis",
    "search engine": "Elasticsearch",
    "data lake": "Snowflake",
    "cloud computing": "AWS",
    "containerization": "Docker",
    "orchestration": "Kubernetes",
    "infrastructure as code": "Terraform",
    "configuration management": "Ansible",
    "monitoring": "Prometheus",
    "dashboarding": "Grafana",
    "log management": "ELK Stack",
    "big data": "Big Data",
    "data pipeline": "Apache Airflow",
    "stream processing": "Apache Kafka",
    "batch processing": "Apache Spark",
    "data warehouse": "Data Warehousing",
    "data modeling": "Data Modeling",
    "etl pipeline": "ETL",
    "business intelligence": "Tableau",
    "data visualization": "Data Visualization",
    "statistical analysis": "Statistical Analysis",
    "hypothesis testing": "A/B Testing",
    "ab testing": "A/B Testing",
    "user research": "User Research",
    "wireframing": "Wireframing",
    "prototyping": "Prototyping",
    "accessibility": "Accessibility",
    "wcag": "Accessibility",
    "responsive design": "CSS3",
    "mobile first": "CSS3",
    "microservices architecture": "Microservices",
    "api gateway": "REST API",
    "message queue": "RabbitMQ",
    "event driven": "Apache Kafka",
    "caching": "Redis",
    "session management": "Redis",
    "authentication": "OAuth",
    "authorization": "JWT",
    "token based auth": "JWT",
    "ssl": "SSL/TLS",
    "tls": "SSL/TLS",
    "https": "SSL/TLS",
    "linux administration": "Linux",
    "unix": "Linux",
    "bash scripting": "Bash",
    "shell scripting": "Bash",
    "powershell scripting": "PowerShell",
    "windows scripting": "PowerShell",
    "web server": "Nginx",
    "reverse proxy": "Nginx",
    "apache http server": "Apache",
    "version control": "Git",
    "code review": "Git",
    "branching strategy": "Git",
    "issue tracking": "Jira",
    "documentation": "Confluence",
    "knowledge management": "Notion",
    "project tracking": "Trello",
    "workflow automation": "Zapier",
    "crm": "Salesforce",
    "marketing automation": "HubSpot",
    "email marketing": "HubSpot",
    "lead generation": "Salesforce",
    "sales automation": "Salesforce",
    "office suite": "Microsoft Office",
    "spreadsheet": "Excel",
    "presentation": "PowerPoint",
    "word processing": "Word",
    "collaboration": "Slack",
    "team communication": "Slack",
    "spreadsheet analysis": "Google Sheets",
    "cloud documents": "Google Docs",
    "database management": "PostgreSQL",
    "data modeling": "Data Modeling",
    "query optimization": "SQL",
    "database design": "SQL",
    "data manipulation": "SQL",
    "object relational mapping": "PostgreSQL",
    "orm": "PostgreSQL",
    "crud operations": "REST API",
    "rest endpoints": "REST API",
    "restful services": "REST API",
    "api development": "REST API",
    "api design": "REST API",
    "api documentation": "REST API",
    "api integration": "REST API",
    "web development": "JavaScript",
    "frontend development": "React",
    "backend development": "Python",
    "full stack": "React",
    "fullstack": "React",
    "mobile development": "Swift",
    "android development": "Kotlin",
    "ios development": "Swift",
    "cross platform": "React",
    "responsive web": "HTML5",
    "web design": "HTML5",
    "ui development": "HTML5",
    "ux design": "UI/UX Design",
    "user interface design": "UI/UX Design",
    "user experience design": "UI/UX Design",
    "interaction design": "UI/UX Design",
    "visual design": "Figma",
    "graphic design": "Photoshop",
    "image editing": "Photoshop",
    "vector graphics": "Illustrator",
    "motion graphics": "Adobe XD",
    "prototyping tool": "Figma",
    "design system": "Figma",
    "design thinking": "UI/UX Design",
    "human computer interaction": "UI/UX Design",
    "cognitive psychology": "User Research",
    "usability testing": "User Research",
    "a11y": "Accessibility",
    "inclusive design": "Accessibility",
    "adaptive design": "Accessibility",
    "progressive enhancement": "HTML5",
    "graceful degradation": "HTML5",
    "seo best practices": "SEO",
    "web analytics": "Google Analytics",
    "conversion optimization": "Google Analytics",
    "funnel analysis": "Google Analytics",
    "cohort analysis": "Google Analytics",
    "customer journey": "User Research",
    "persona development": "User Research",
    "journey mapping": "User Research",
    "service design": "UI/UX Design",
    "experience design": "UI/UX Design",
    "content strategy": "Technical Writing",
    "information architecture": "Wireframing",
    "navigation design": "Wireframing",
    "interaction pattern": "Prototyping",
    "design pattern": "Prototyping",
    "ux writing": "Technical Writing",
    "microcopy": "Technical Writing",
    "error handling": "Python",
    "exception handling": "Python",
    "logging": "Prometheus",
    "debugging": "Python",
    "profiling": "Python",
    "optimization": "Python",
    "performance tuning": "Python",
    "code quality": "Git",
    "code standards": "Git",
    "best practices": "Git",
    "coding standards": "Git",
    "clean code": "Git",
    "refactoring": "Python",
    "code review": "Git",
    "pull request": "Git",
    "merge request": "Git",
    "code merge": "Git",
    "conflict resolution git": "Git",
    "git workflow": "Git",
    "git flow": "Git",
    "trunk based": "Git",
    "feature branch": "Git",
    "release management": "CI/CD",
    "deployment strategy": "CI/CD",
    "blue green deployment": "CI/CD",
    "canary deployment": "CI/CD",
    "rolling deployment": "CI/CD",
    "infrastructure monitoring": "Prometheus",
    "application monitoring": "Prometheus",
    "synthetic monitoring": "Prometheus",
    "real user monitoring": "Prometheus",
    "apm": "Prometheus",
    "log aggregation": "ELK Stack",
    "centralized logging": "ELK Stack",
    "distributed tracing": "ELK Stack",
    "tracing": "ELK Stack",
    "profiling": "Grafana",
    "metrics": "Grafana",
    "alerting": "Prometheus",
    "incident management": "PagerDuty",
    "on call": "PagerDuty",
    "postmortem": "PagerDuty",
    "root cause analysis": "PagerDuty",
    "blameless postmortem": "PagerDuty",
    "service level objective": "SRE",
    "slo": "SRE",
    "sla": "SRE",
    "error budget": "SRE",
    "toil reduction": "SRE",
    "automation": "SRE",
    "capacity planning": "SRE",
    "disaster recovery": "AWS",
    "business continuity": "AWS",
    "high availability": "AWS",
    "fault tolerance": "AWS",
    "resilience": "AWS",
    "scalability": "AWS",
    "elasticity": "AWS",
    "load balancing": "AWS",
    "auto scaling": "AWS",
    "cdn": "AWS",
    "edge computing": "AWS",
    "content delivery": "AWS",
    "static hosting": "AWS",
    "domain management": "AWS",
    "dns management": "AWS",
    "ssl certificate": "SSL/TLS",
    "certificate management": "SSL/TLS",
    "secrets management": "AWS",
    "key management": "AWS",
    "encryption": "AWS",
    "data protection": "AWS",
    "compliance": "AWS",
    "gdpr": "AWS",
    "hipaa": "AWS",
    "soc2": "AWS",
    "pci dss": "AWS",
    "iso 27001": "AWS",
    "nist": "AWS",
    "security audit": "Cybersecurity",
    "vulnerability assessment": "Cybersecurity",
    "threat modeling": "Cybersecurity",
    "incident response": "Cybersecurity",
    "security operations": "Cybersecurity",
    "soc": "Cybersecurity",
    "siem": "SIEM",
    "log analysis": "Splunk",
    "security information": "SIEM",
    "security event management": "SIEM",
    "intrusion detection": "Network Security",
    "firewall management": "Network Security",
    "vpn management": "Network Security",
    "access control": "Network Security",
    "identity management": "OAuth",
    "single sign on": "OAuth",
    "sso": "OAuth",
    "multi factor authentication": "OAuth",
    "mfa": "OAuth",
    "rbac": "OAuth",
    "abac": "OAuth",
    "zero trust": "Network Security",
    "network segmentation": "Network Security",
    "network monitoring": "Wireshark",
    "packet analysis": "Wireshark",
    "protocol analysis": "Wireshark",
    "traffic analysis": "Wireshark",
    "bandwidth monitoring": "Wireshark",
    "latency analysis": "Wireshark",
    "network troubleshooting": "Wireshark",
    "network diagnostics": "Wireshark",
    "network performance": "Wireshark",
    "network optimization": "Wireshark",
    "network security auditing": "Wireshark",
    "compliance auditing": "Wireshark",
    "forensic analysis": "Wireshark",
    "incident investigation": "Wireshark",
    "malware analysis": "Wireshark",
    "threat detection": "Wireshark",
    "anomaly detection": "Wireshark",
    "behavioral analysis": "Wireshark",
    "deep packet inspection": "Wireshark",
    "dpi": "Wireshark",
    "network forensics": "Wireshark",
    "packet capture": "Wireshark",
    "pcap analysis": "Wireshark",
    "network packet analysis": "Wireshark",
    "network traffic analysis": "Wireshark",
    "network protocol analysis": "Wireshark",
    "network intrusion detection": "Wireshark",
    "network intrusion prevention": "Wireshark",
    "network access control": "Wireshark",
    "network security monitoring": "Wireshark",
    "network security analysis": "Wireshark",
    "network security assessment": "Wireshark",
    "network security audit": "Wireshark",
    "network security testing": "Wireshark",
    "network security scanning": "Wireshark",
    "network security enumeration": "Wireshark",
    "network security exploitation": "Wireshark",
    "network security defense": "Wireshark",
    "network security protection": "Wireshark",
    "network security mitigation": "Wireshark",
    "network security response": "Wireshark",
    "network security recovery": "Wireshark",
    "network security hardening": "Wireshark",
    "network security configuration": "Wireshark",
    "network security management": "Wireshark",
    "network security operations": "Wireshark",
    "network security governance": "Wireshark",
    "network security compliance": "Wireshark",
    "network security policy": "Wireshark",
    "network security procedure": "Wireshark",
    "network security guideline": "Wireshark",
    "network security standard": "Wireshark",
    "network security framework": "Wireshark",
    "network security architecture": "Wireshark",
    "network security design": "Wireshark",
    "network security implementation": "Wireshark",
    "network security deployment": "Wireshark",
    "network security installation": "Wireshark",
    "network security setup": "Wireshark",
    "network security initialization": "Wireshark",
    "network security commissioning": "Wireshark",
    "network security activation": "Wireshark",
    "network security enablement": "Wireshark",
    "network security enforcement": "Wireshark",
    "network security validation": "Wireshark",
    "network security verification": "Wireshark",
    "network security testing": "Wireshark",
    "network security assessment": "Wireshark",
    "network security evaluation": "Wireshark",
    "network security review": "Wireshark",
    "network security audit": "Wireshark",
    "network security inspection": "Wireshark",
    "network security examination": "Wireshark",
    "network security analysis": "Wireshark",
    "network security monitoring": "Wireshark",
    "network security surveillance": "Wireshark",
    "network security observation": "Wireshark",
    "network security tracking": "Wireshark",
    "network security logging": "Wireshark",
    "network security reporting": "Wireshark",
    "network security alerting": "Wireshark",
    "network security notification": "Wireshark",
    "network security warning": "Wireshark",
    "network security alarm": "Wireshark",
    "network security incident": "Wireshark",
    "network security event": "Wireshark",
    "network security threat": "Wireshark",
    "network security vulnerability": "Wireshark",
    "network security risk": "Wireshark",
    "network security exposure": "Wireshark",
    "network security weakness": "Wireshark",
    "network security flaw": "Wireshark",
    "network security gap": "Wireshark",
    "network security deficiency": "Wireshark",
    "network security failure": "Wireshark",
    "network security breach": "Wireshark",
    "network security compromise": "Wireshark",
    "network security attack": "Wireshark",
    "network security exploit": "Wireshark",
    "network security intrusion": "Wireshark",
    "network security violation": "Wireshark",
    "network security offense": "Wireshark",
    "network security crime": "Wireshark",
    "network security fraud": "Wireshark",
    "network security scam": "Wireshark",
    "network security phishing": "Wireshark",
    "network security social engineering": "Wireshark",
    "network security manipulation": "Wireshark",
    "network security deception": "Wireshark",
    "network security trickery": "Wireshark",
    "network security subterfuge": "Wireshark",
    "network security disguise": "Wireshark",
    "network security camouflage": "Wireshark",
    "network security stealth": "Wireshark",
    "network security covert": "Wireshark",
    "network security hidden": "Wireshark",
    "network security concealed": "Wireshark",
    "network security secret": "Wireshark",
    "network security classified": "Wireshark",
    "network security confidential": "Wireshark",
    "network security restricted": "Wireshark",
    "network security limited": "Wireshark",
    "network security controlled": "Wireshark",
    "network security regulated": "Wireshark",
    "network security governed": "Wireshark",
    "network security managed": "Wireshark",
    "network security administered": "Wireshark",
    "network security supervised": "Wireshark",
    "network security directed": "Wireshark",
    "network security guided": "Wireshark",
    "network security led": "Wireshark",
    "network security steered": "Wireshark",
    "network security piloted": "Wireshark",
    "network security navigated": "Wireshark",
    "network security driven": "Wireshark",
    "network security operated": "Wireshark",
    "network security run": "Wireshark",
    "network security executed": "Wireshark",
    "network security performed": "Wireshark",
    "network security conducted": "Wireshark",
    "network security carried out": "Wireshark",
    "network security implemented": "Wireshark",
    "network security applied": "Wireshark",
    "network security utilized": "Wireshark",
    "network security employed": "Wireshark",
    "network security used": "Wireshark",
    "network security leveraged": "Wireshark",
    "network security harnessed": "Wireshark",
    "network security exploited": "Wireshark",
    "network security tapped": "Wireshark",
    "network security accessed": "Wireshark",
    "network security reached": "Wireshark",
    "network security contacted": "Wireshark",
    "network security connected": "Wireshark",
    "network security linked": "Wireshark",
    "network security joined": "Wireshark",
    "network security coupled": "Wireshark",
    "network security paired": "Wireshark",
    "network security matched": "Wireshark",
    "network security aligned": "Wireshark",
    "network security synchronized": "Wireshark",
    "network security coordinated": "Wireshark",
    "network security integrated": "Wireshark",
    "network security unified": "Wireshark",
    "network security consolidated": "Wireshark",
    "network security merged": "Wireshark",
    "network security combined": "Wireshark",
    "network security blended": "Wireshark",
    "network security mixed": "Wireshark",
    "network security mingled": "Wireshark",
    "network security intertwined": "Wireshark",
    "network security interwoven": "Wireshark",
    "network security interconnected": "Wireshark",
    "network security interlinked": "Wireshark",
    "network security interrelated": "Wireshark",
    "network security interdependent": "Wireshark",
    "network security interconnecting": "Wireshark",
    "network security interlinking": "Wireshark",
    "network security interrelating": "Wireshark",
    "network security interdependent": "Wireshark",
    "network security interconnectedness": "Wireshark",
    "network security interdependence": "Wireshark",
    "network security interconnection": "Wireshark",
    "network security interlink": "Wireshark",
    "network security interrelation": "Wireshark",
    "network security interrelationship": "Wireshark",
    "network security interplay": "Wireshark",
    "network security interaction": "Wireshark",
    "network security interactivity": "Wireshark",
    "network security interactive": "Wireshark",
    "network security interactor": "Wireshark",
    "network security interacting": "Wireshark",
    "network security interacted": "Wireshark",
    "network security interact": "Wireshark",
    "network security interface": "Wireshark",
    "network security interfacing": "Wireshark",
    "network security interfaced": "Wireshark",
    "network security interfacing": "Wireshark",
    "network security intercommunication": "Wireshark",
    "network security intercommunicate": "Wireshark",
    "network security intercommunication": "Wireshark",
    "network security intercommunicating": "Wireshark",
    "network security intercommunicated": "Wireshark",
    "network security intercommunicates": "Wireshark",
    "network security intercommunion": "Wireshark",
    "network security intercommuning": "Wireshark",
    "network security intercommuned": "Wireshark",
    "network security intercommunes": "Wireshark",
    "network security interchange": "Wireshark",
    "network security interchanging": "Wireshark",
    "network security interchanged": "Wireshark",
    "network security interchanges": "Wireshark",
    "network security intercoursed": "Wireshark",
    "network security intercoursing": "Wireshark",
    "network security intercourses": "Wireshark",
    "network security intercourse": "Wireshark",
    "network security interfaith": "Wireshark",
    "network security interfacing": "Wireshark",
    "network security interfaced": "Wireshark",
    "network security interfacing": "Wireshark",
    "network security interfaith": "Wireshark",
    "network security interfamily": "Wireshark",
    "network security interfederal": "Wireshark",
    "network security intergalactic": "Wireshark",
    "network security intergeneric": "Wireshark",
    "network security intergovernmental": "Wireshark",
    "network security intergroup": "Wireshark",
    "network security interindustry": "Wireshark",
    "network security interlingual": "Wireshark",
    "network security intermarriage": "Wireshark",
    "network security intermarrying": "Wireshark",
    "network security intermarried": "Wireshark",
    "network security intermarries": "Wireshark",
    "network security intermarry": "Wireshark",
    "network security intermediary": "Wireshark",
    "network security intermediated": "Wireshark",
    "network security intermediates": "Wireshark",
    "network security intermediate": "Wireshark",
    "network security intermediating": "Wireshark",
    "network security intermediation": "Wireshark",
    "network security intermetallic": "Wireshark",
    "network security intermolecular": "Wireshark",
    "network security internal": "Wireshark",
    "network security internalization": "Wireshark",
    "network security internalize": "Wireshark",
    "network security internalized": "Wireshark",
    "network security internalizes": "Wireshark",
    "network security internalizing": "Wireshark",
    "network security international": "Wireshark",
    "network security internationalization": "Wireshark",
    "network security internationalize": "Wireshark",
    "network security internationalized": "Wireshark",
    "network security internationalizes": "Wireshark",
    "network security internationalizing": "Wireshark",
    "network security internet": "Wireshark",
    "network security internetwork": "Wireshark",
    "network security internetworking": "Wireshark",
    "network security internetworked": "Wireshark",
    "network security internetworks": "Wireshark",
    "network security interpersonal": "Wireshark",
    "network security interpolation": "Wireshark",
    "network security interpolated": "Wireshark",
    "network security interpolates": "Wireshark",
    "network security interpolate": "Wireshark",
    "network security interpolating": "Wireshark",
    "network security interplant": "Wireshark",
    "network security interplanetary": "Wireshark",
    "network security interplay": "Wireshark",
    "network security interplayed": "Wireshark",
    "network security interplays": "Wireshark",
    "network security interplead": "Wireshark",
    "network security interpleaded": "Wireshark",
    "network security interpleads": "Wireshark",
    "network security interpolate": "Wireshark",
    "network security interpolating": "Wireshark",
    "network security interpolated": "Wireshark",
    "network security interpolates": "Wireshark",
    "network security interpose": "Wireshark",
    "network security interposed": "Wireshark",
    "network security interposes": "Wireshark",
    "network security interposing": "Wireshark",
    "network security interposition": "Wireshark",
    "network security interpret": "Wireshark",
    "network security interpretated": "Wireshark",
    "network security interpretates": "Wireshark",
    "network security interpretating": "Wireshark",
    "network security interpretation": "Wireshark",
    "network security interpretational": "Wireshark",
    "network security interpretative": "Wireshark",
    "network security interpretatively": "Wireshark",
    "network security interpreted": "Wireshark",
    "network security interpreter": "Wireshark",
    "network security interpreters": "Wireshark",
    "network security interprets": "Wireshark",
    "network security interracial": "Wireshark",
    "network security interregional": "Wireshark",
    "network security interrelated": "Wireshark",
    "network security interrelates": "Wireshark",
    "network security interrelate": "Wireshark",
    "network security interrelating": "Wireshark",
    "network security interrelation": "Wireshark",
    "network security interrelationship": "Wireshark",
    "network security interreligious": "Wireshark",
    "network security interrogate": "Wireshark",
    "network security interrogated": "Wireshark",
    "network security interrogates": "Wireshark",
    "network security interrogating": "Wireshark",
    "network security interrogation": "Wireshark",
    "network security interrogational": "Wireshark",
    "network security interrogative": "Wireshark",
    "network security interrogatively": "Wireshark",
    "network security interrogator": "Wireshark",
    "network security interrogators": "Wireshark",
    "network security interrupt": "Wireshark",
    "network security interrupted": "Wireshark",
    "network security interrupter": "Wireshark",
    "network security interrupters": "Wireshark",
    "network security interrupting": "Wireshark",
    "network security interruption": "Wireshark",
    "network security interruptions": "Wireshark",
    "network security interruptive": "Wireshark",
    "network security interrupts": "Wireshark",
    "network security intersect": "Wireshark",
    "network security intersected": "Wireshark",
    "network security intersecting": "Wireshark",
    "network security intersection": "Wireshark",
    "network security intersections": "Wireshark",
    "network security intersects": "Wireshark",
    "network security intersegment": "Wireshark",
    "network security interservice": "Wireshark",
    "network security intersession": "Wireshark",
    "network security intersexual": "Wireshark",
    "network security interspecies": "Wireshark",
    "network security interstage": "Wireshark",
    "network security interstate": "Wireshark",
    "network security interstellar": "Wireshark",
    "network security interstitial": "Wireshark",
    "network security intersystem": "Wireshark",
    "network security interterritorial": "Wireshark",
    "network security intertestamental": "Wireshark",
    "network security intertidal": "Wireshark",
    "network security intertribal": "Wireshark",
    "network security intertropical": "Wireshark",
    "network security intervening": "Wireshark",
    "network security intervention": "Wireshark",
    "network security interventional": "Wireshark",
    "network security interventionism": "Wireshark",
    "network security interventionist": "Wireshark",
    "network security interventions": "Wireshark",
    "network security intervertebral": "Wireshark",
    "network security interview": "Wireshark",
    "network security interviewed": "Wireshark",
    "network security interviewer": "Wireshark",
    "network security interviewers": "Wireshark",
    "network security interviewing": "Wireshark",
    "network security interviews": "Wireshark",
    "network security interwar": "Wireshark",
    "network security interweave": "Wireshark",
    "network security interweaved": "Wireshark",
    "network security interweaves": "Wireshark",
    "network security interweaving": "Wireshark",
    "network security interwork": "Wireshark",
    "network security interworked": "Wireshark",
    "network security interworking": "Wireshark",
    "network security interworks": "Wireshark",
    "network security interstate": "Wireshark",
    "network security interstate": "Wireshark",
    "network security interstate": "Wireshark",
}

SKILL_PATTERNS = {
    "machine learning": ["machine learning", "ml", "machine-learning"],
    "deep learning": ["deep learning", "dl", "deep-learning"],
    "natural language processing": ["nlp", "natural language processing", "natural language"],
    "computer vision": ["computer vision", "cv", "image processing"],
    "data science": ["data science", "data scientist", "data-science"],
    "data analysis": ["data analysis", "data analyst", "data-analytics"],
    "data engineering": ["data engineering", "data engineer", "data-engineering"],
    "web development": ["web development", "web developer", "web dev"],
    "frontend development": ["frontend", "front-end", "front end", "frontend development"],
    "backend development": ["backend", "back-end", "back end", "backend development"],
    "full stack development": ["full stack", "fullstack", "full-stack", "full stack development"],
    "mobile development": ["mobile development", "mobile app", "mobile developer"],
    "cloud computing": ["cloud computing", "cloud", "cloud services"],
    "devops": ["devops", "dev ops", "dev-ops", "devops engineering"],
    "cybersecurity": ["cybersecurity", "cyber security", "information security", "infosec"],
    "project management": ["project management", "project manager", "project-manager"],
    "product management": ["product management", "product manager", "product-manager"],
    "agile methodology": ["agile", "agile methodology", "agile development"],
    "scrum methodology": ["scrum", "scrum methodology", "scrum master"],
    "ui/ux design": ["ui/ux", "ui ux", "ux design", "ui design", "user experience", "user interface"],
    "technical writing": ["technical writing", "technical writer", "documentation"],
    "leadership": ["leadership", "team leadership", "leadership skills"],
    "communication": ["communication", "communication skills", "verbal communication"],
    "problem solving": ["problem solving", "problem-solving", "analytical skills"],
    "critical thinking": ["critical thinking", "critical-thinking", "analytical thinking"],
    "teamwork": ["teamwork", "team collaboration", "team work"],
    "time management": ["time management", "time-management", "organizational skills"],
    "attention to detail": ["attention to detail", "detail-oriented", "meticulous"],
    "analytical thinking": ["analytical thinking", "analytical skills", "analysis"],
    "decision making": ["decision making", "decision-making", "judgment"],
    "emotional intelligence": ["emotional intelligence", "eq", "emotional quotient"],
    "public speaking": ["public speaking", "presentation skills", "speaking skills"],
    "negotiation": ["negotiation", "negotiation skills", "bargaining"],
    "mentoring": ["mentoring", "mentorship", "coaching"],
    "budget management": ["budget management", "budgeting", "financial management"],
    "risk management": ["risk management", "risk assessment", "risk analysis"],
    "quality assurance": ["quality assurance", "qa", "quality control"],
    "testing": ["testing", "software testing", "test automation"],
    "api development": ["api development", "api design", "api integration"],
    "database management": ["database management", "database admin", "dba"],
    "version control": ["version control", "git", "source control"],
    "code review": ["code review", "peer review", "code inspection"],
    "performance optimization": ["performance optimization", "performance tuning", "optimization"],
    "security": ["security", "application security", "network security"],
    "networking": ["networking", "network administration", "network engineering"],
    "system administration": ["system administration", "sysadmin", "system admin"],
    "automation": ["automation", "process automation", "workflow automation"],
    "integration": ["integration", "system integration", "api integration"],
    "monitoring": ["monitoring", "system monitoring", "application monitoring"],
    "logging": ["logging", "log management", "log analysis"],
    "backup and recovery": ["backup", "disaster recovery", "business continuity"],
    "capacity planning": ["capacity planning", "resource planning", "scaling"],
    "infrastructure management": ["infrastructure management", "infrastructure", "it infrastructure"],
    "virtualization": ["virtualization", "vmware", "virtual machines"],
    "containerization": ["containerization", "docker", "containers"],
    "orchestration": ["orchestration", "kubernetes", "container orchestration"],
    "ci/cd": ["ci/cd", "continuous integration", "continuous deployment", "cicd"],
    "infrastructure as code": ["infrastructure as code", "iac", "terraform"],
    "configuration management": ["configuration management", "ansible", "puppet"],
    "monitoring and alerting": ["monitoring", "alerting", "observability"],
    "log management": ["log management", "log aggregation", "centralized logging"],
    "incident management": ["incident management", "incident response", "on-call"],
    "postmortem analysis": ["postmortem", "post-mortem", "root cause analysis"],
    "service level management": ["slo", "sla", "service level"],
    "error budget management": ["error budget", "reliability", "availability"],
    "toil reduction": ["toil reduction", "automation", "efficiency"],
    "capacity planning": ["capacity planning", "scaling", "resource planning"],
    "disaster recovery": ["disaster recovery", "business continuity", "backup"],
    "high availability": ["high availability", "ha", "fault tolerance"],
    "resilience engineering": ["resilience", "fault tolerance", "redundancy"],
    "scalability": ["scalability", "scaling", "horizontal scaling"],
    "elasticity": ["elasticity", "auto-scaling", "dynamic scaling"],
    "load balancing": ["load balancing", "load balancer", "traffic distribution"],
    "cdn": ["cdn", "content delivery network", "edge caching"],
    "edge computing": ["edge computing", "edge", "distributed computing"],
    "static hosting": ["static hosting", "static site", "jamstack"],
    "domain management": ["domain management", "dns", "domain registration"],
    "ssl/tls": ["ssl", "tls", "ssl/tls", "certificate management"],
    "secrets management": ["secrets management", "vault", "key management"],
    "encryption": ["encryption", "data encryption", "cryptography"],
    "data protection": ["data protection", "data privacy", "data security"],
    "compliance": ["compliance", "regulatory compliance", "audit"],
    "gdpr": ["gdpr", "data privacy regulation", "privacy law"],
    "hipaa": ["hipaa", "healthcare compliance", "medical data"],
    "soc2": ["soc2", "soc 2", "security audit"],
    "pci dss": ["pci dss", "payment card", "card data security"],
    "iso 27001": ["iso 27001", "iso certification", "security standard"],
    "nist": ["nist", "security framework", "security standard"],
    "security audit": ["security audit", "security assessment", "vulnerability assessment"],
    "vulnerability assessment": ["vulnerability assessment", "vulnerability scanning", "pen testing"],
    "threat modeling": ["threat modeling", "threat analysis", "risk assessment"],
    "incident response": ["incident response", "security incident", "breach response"],
    "security operations": ["security operations", "soc", "security monitoring"],
    "siem": ["siem", "security information and event management", "log analysis"],
    "intrusion detection": ["intrusion detection", "ids", "network monitoring"],
    "firewall management": ["firewall", "firewall management", "network security"],
    "vpn management": ["vpn", "virtual private network", "remote access"],
    "access control": ["access control", "rbac", "abac", "authorization"],
    "identity management": ["identity management", "iam", "identity and access"],
    "single sign-on": ["sso", "single sign-on", "federated identity"],
    "multi-factor authentication": ["mfa", "multi-factor authentication", "2fa", "two-factor"],
    "zero trust": ["zero trust", "zero trust architecture", "zero trust security"],
    "network segmentation": ["network segmentation", "network isolation", "microsegmentation"],
    "network monitoring": ["network monitoring", "network management", "network observation"],
    "packet analysis": ["packet analysis", "packet capture", "pcap analysis"],
    "protocol analysis": ["protocol analysis", "protocol inspection", "protocol decoding"],
    "traffic analysis": ["traffic analysis", "network traffic", "traffic monitoring"],
    "bandwidth monitoring": ["bandwidth monitoring", "bandwidth management", "traffic analysis"],
    "latency analysis": ["latency analysis", "latency monitoring", "performance analysis"],
    "network troubleshooting": ["network troubleshooting", "network diagnostics", "network debugging"],
    "network diagnostics": ["network diagnostics", "network testing", "network analysis"],
    "network performance": ["network performance", "network optimization", "network tuning"],
    "network optimization": ["network optimization", "network tuning", "performance improvement"],
    "network security auditing": ["network security audit", "security audit", "compliance audit"],
    "compliance auditing": ["compliance audit", "regulatory audit", "security audit"],
    "forensic analysis": ["forensic analysis", "digital forensics", "incident investigation"],
    "incident investigation": ["incident investigation", "forensic investigation", "breach investigation"],
    "malware analysis": ["malware analysis", "malware reverse engineering", "threat analysis"],
    "threat detection": ["threat detection", "threat identification", "anomaly detection"],
    "anomaly detection": ["anomaly detection", "anomaly identification", "behavioral analysis"],
    "behavioral analysis": ["behavioral analysis", "behavior analysis", "user behavior"],
    "deep packet inspection": ["dpi", "deep packet inspection", "packet inspection"],
    "network forensics": ["network forensics", "network investigation", "packet forensics"],
    "packet capture": ["packet capture", "pcap", "network capture"],
    "pcap analysis": ["pcap analysis", "packet analysis", "capture analysis"],
}

CANONICAL_NAMES = {s.lower(): s for s in SKILLS}
CANONICAL_NAMES.update({
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "natural language processing": "NLP",
    "computer vision": "Computer Vision",
    "data science": "Data Science",
    "data analysis": "Data Analysis",
    "data engineering": "Data Engineering",
    "web development": "Web Development",
    "frontend development": "Frontend Development",
    "backend development": "Backend Development",
    "full stack development": "Full Stack Development",
    "mobile development": "Mobile Development",
    "cloud computing": "Cloud Computing",
    "devops": "DevOps",
    "cybersecurity": "Cybersecurity",
    "project management": "Project Management",
    "product management": "Product Management",
    "agile methodology": "Agile",
    "scrum methodology": "Scrum",
    "ui/ux design": "UI/UX Design",
    "technical writing": "Technical Writing",
    "leadership": "Leadership",
    "communication": "Communication",
    "problem solving": "Problem Solving",
    "critical thinking": "Critical Thinking",
    "teamwork": "Teamwork",
    "time management": "Time Management",
    "attention to detail": "Attention to Detail",
    "analytical thinking": "Analytical Thinking",
    "decision making": "Decision Making",
    "emotional intelligence": "Emotional Intelligence",
    "public speaking": "Public Speaking",
    "negotiation": "Negotiation",
    "mentoring": "Mentoring",
    "budget management": "Budget Management",
    "risk management": "Risk Management",
    "quality assurance": "Quality Assurance",
    "testing": "Testing",
    "api development": "API Development",
    "database management": "Database Management",
    "version control": "Version Control",
    "code review": "Code Review",
    "performance optimization": "Performance Optimization",
    "security": "Security",
    "networking": "Networking",
    "system administration": "System Administration",
    "automation": "Automation",
    "integration": "Integration",
    "monitoring": "Monitoring",
    "logging": "Logging",
    "backup and recovery": "Backup and Recovery",
    "capacity planning": "Capacity Planning",
    "infrastructure management": "Infrastructure Management",
    "virtualization": "Virtualization",
    "containerization": "Docker",
    "orchestration": "Kubernetes",
    "ci/cd": "CI/CD",
    "infrastructure as code": "Terraform",
    "configuration management": "Ansible",
    "monitoring and alerting": "Prometheus",
    "log management": "ELK Stack",
    "incident management": "Incident Management",
    "postmortem analysis": "Postmortem Analysis",
    "service level management": "SRE",
    "error budget management": "SRE",
    "toil reduction": "SRE",
    "disaster recovery": "Disaster Recovery",
    "high availability": "High Availability",
    "resilience engineering": "Resilience",
    "scalability": "Scalability",
    "elasticity": "Elasticity",
    "load balancing": "Load Balancing",
    "cdn": "CDN",
    "edge computing": "Edge Computing",
    "static hosting": "Static Hosting",
    "domain management": "Domain Management",
    "ssl/tls": "SSL/TLS",
    "secrets management": "Secrets Management",
    "encryption": "Encryption",
    "data protection": "Data Protection",
    "compliance": "Compliance",
    "gdpr": "GDPR",
    "hipaa": "HIPAA",
    "soc2": "SOC2",
    "pci dss": "PCI DSS",
    "iso 27001": "ISO 27001",
    "nist": "NIST",
    "security audit": "Security Audit",
    "vulnerability assessment": "Vulnerability Assessment",
    "threat modeling": "Threat Modeling",
    "incident response": "Incident Response",
    "security operations": "Security Operations",
    "siem": "SIEM",
    "intrusion detection": "Intrusion Detection",
    "firewall management": "Firewall Management",
    "vpn management": "VPN Management",
    "access control": "Access Control",
    "identity management": "Identity Management",
    "single sign-on": "Single Sign-On",
    "multi-factor authentication": "Multi-Factor Authentication",
    "zero trust": "Zero Trust",
    "network segmentation": "Network Segmentation",
    "network monitoring": "Network Monitoring",
    "packet analysis": "Packet Analysis",
    "protocol analysis": "Protocol Analysis",
    "traffic analysis": "Traffic Analysis",
    "bandwidth monitoring": "Bandwidth Monitoring",
    "latency analysis": "Latency Analysis",
    "network troubleshooting": "Network Troubleshooting",
    "network diagnostics": "Network Diagnostics",
    "network performance": "Network Performance",
    "network optimization": "Network Optimization",
    "network security auditing": "Network Security Auditing",
    "compliance auditing": "Compliance Auditing",
    "forensic analysis": "Forensic Analysis",
    "incident investigation": "Incident Investigation",
    "malware analysis": "Malware Analysis",
    "threat detection": "Threat Detection",
    "anomaly detection": "Anomaly Detection",
    "behavioral analysis": "Behavioral Analysis",
    "deep packet inspection": "Deep Packet Inspection",
    "network forensics": "Network Forensics",
    "packet capture": "Packet Capture",
    "pcap analysis": "PCAP Analysis",
})

def extract_skills(text: str):
    text_lower = text.lower()

    found = set()

    for skill_name, patterns in SKILL_PATTERNS.items():
        for pattern in patterns:
            if pattern.lower() in text_lower:
                canonical = CANONICAL_NAMES.get(skill_name.lower(), skill_name)
                found.add(canonical)
                break

    for skill in SKILLS:
        skill_lower = skill.lower()
        if skill_lower in text_lower:
            found.add(skill)

    for alias, canonical in SKILL_ALIASES.items():
        if alias.lower() in text_lower:
            found.add(canonical)

    return sorted(found)
